### ISSUE TITLE
Neovim API b'Key not found' following current instructions

### ISSUE THREAD

**Issue by ajcrites** [mhartington/deoplete-typescript#23]
I can't get this to work at all based on the README instructions. I'm sorry for a somewhat general / support issue, but maybe this is a bug in this library, deoplete, neovim, or something that will help someone else out.

    $ nvim --version
    NVIM 0.1.5

* `python3` support is installed.
* `typescript` package is installed globally.

Gist of `.vimrc` files: https://gist.github.com/ajcrites/9d5d0418af1f9256c8cd4b954100fb48 -- the top file is what I'm using to still test / reproduce this. The `.bak` file is my usual vimrc which seems to have exactly the same problem.

Example of a `.ts` and `tsconfig.json` I'm using: https://gist.github.com/ajcrites/7a985e8a487c050c6126b462b532cb68

If I type `finalB<C-p>` it will complete. After `finalBusinessCategories.`, `<C-o>` or `<C-x>` do not work. `<C-p>` will just list all of the words in the file.

When I open the file, I get:

```
Error detected while processing function deoplete#enable_logging:
line    6:
error caught in async handler 'deoplete_on_event [{'max_menu_width': 52, 'filetype': 'nothing', 'encoding': 'utf-8', 'bufnr': 1, 'cwd': '/Users/acrites/projects/personal/business-web', 'input': '', 'dict__dictionary': '', 'complete_str': '', 'bufvars': {}, 'camelcase': 0, 'bufname': '/Users/acrites/.vimrc', 'filetypes': ['nothing'], 'rpc': 'deoplete_on_event', 'keyword_patterns': '[a-zA-Z_][a-zA-Z@0-9_À-ÿ]*', 'delay': 50, 'start_complete': '\udc80\udcfdR(deoplete_start_complete)', 'sources': [], 'position': [0, 1, 1, 0], 'omni__omnifunc': '', 'ignorecase': 1, 'custom': {'_': {}}, 'max_abbr_width': 52, 'vars': {'deoplete#max_list': 100, 'deoplete#disable_auto_complete': 0, 'deoplete#member#prefix_patterns': {}, 'deoplete#enable_refresh_always': 1, 'deoplete#enable_at_startup': 1, 'deoplete#max_abbr_width': 80, 'deoplete#enable_smart_case': 0, 'deoplete#omni#functions': {}, 'deoplete#delimiters': ['/', '.', '::', ':', '#'], 'deoplete#_neovim_python_version': '0.1.9', 'deoplete#max_menu_width': 40, 'deoplete#omni_patterns': {}, 'deoplete#auto_complete_delay': 50, 'deoplete#keyword_patterns': {}, 'deoplete#_omni_patterns': {'xhtml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'xml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'mkd': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'markdown': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'html': ['<', '<[^>]*\\s[[:alnum:]-]*']}, 'deoplete#enable_debug': 1, 'deoplete#_keyword_patterns': {'_': '[a-zA-Z_]\\k*'}, 'deoplete#_channel_id': 1, 'deoplete#enable_ignore_case': 1, 'deoplete#enable_profile': 1, 'deoplete#_rank': {}, 'deoplete#enable_camel_case': 0, 'deoplete#_context': {}, 'deoplete#auto_complete_start_length': 0, 'deoplete#omni#input_patterns': {}, 'deoplete#ignore_sources': {}, 'deoplete#sources': {}}, 'runtimepath': '/Users/acrites/.config/nvim/dein/repos/github.com/Shougo/vimproc.vim,/Users/acrites/.config/nvim/dein/.dein,/Users/acrites/.config/nvim/dein/repos/github.com/Shougo/dein.vim,/Users/acrites/.config/nvim,/etc/xdg/nvim,/Users/acrites/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/0.1.5/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/Users/acrites/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/acrites/.config/nvim/after,/Users/acrites/.config/nvim/dein/.dein/after', 'next_input': '', 'smartcase': 0, 'changedtick': 2, 'event': ''}]'
Traceback (most recent call last):
  File "/Users/acrites/.config/nvim/dein/.dein/rplugin/python3/deoplete/__init__.py", line 57, in on_event
    self.__deoplete.on_event(context)
  File "/Users/acrites/.config/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 372, in on_event
    self.check_recache(context)
  File "/Users/acrites/.config/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 360, in check_recache
    self.load_sources(context)
  File "/Users/acrites/.config/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 254, in load_sources
    source = module.Source(self.__vim)
  File "/Users/acrites/.config/nvim/dein/.dein/rplugin/python3/deoplete/sources/typescript.py", line 26, in __init__
    self.filetypes = ["typescript", "tsx", "typescript.tsx", "javascript", "jsx", "javascript.jsx"] if vim.vars["deoplete#sources#tss#javascript_support"] else ["typescript"]
neovim.api.nvim.NvimError: b'Key not found'
[deoplete] Logging to deoplete.log
Press ENTER or type command to continue
```

However I think this is just related to the debug logging. If I remove that line, I get no errors when I start the file.

Anything suggestions would be a ton of help. I'm also not sure of the best way to walk through debugging this since I've followed the README instructions exactly, but this doesn't seem to work at all.

**Comment by mhartington** [comment]
Do you have a typescript syntax file? 
I tested out your vimrc and found that if you're not setting the filetype, deoplete-typescript does not know how to process the file, which makes sense.

To test this out, I added a simple Autocommand for `*.ts`  and manually set the filetype.

https://gist.github.com/mhartington/009aa9e11eef3dab49926f63ccb754f2

And then completion started happening.
