### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe when modifying a typescript file

### ISSUE THREAD

**Issue by mvalkon** [mhartington/deoplete-typescript#33]
Using the following neovim (python3 support included):

```
→ nvim --version
NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/build/config -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/src -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-HzUNdy/neovim-0.1.5ubuntu1+git201611271903+2919+22~ubuntu14.04.1/build/include
Compiled by root@lgw01-12

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

and the latest `deoplete-typescript`, I'm getting the following python exception traceback every time I edit a `.ts` file. The error occurs immediately when the file is opened and subsequently for every modification attempt, making usage completely impossible.

```
error caught in async handler '/home/emikkva/.config/nvim/plugged/deoplete-typescript/rplugin/python3/nvim-typescript:autocmd:BufWritePost:*.ts,*.tsx []'                                     
Traceback (most recent call last):                                                                                                                                                            
  File "/home/emikkva/.config/nvim/plugged/deoplete-typescript/rplugin/python3/nvim-typescript/__init__.py", line 220, in on_bufwritepost                                                     
    self.reload()                                                                                                                                                                             
  File "/home/emikkva/.config/nvim/plugged/deoplete-typescript/rplugin/python3/nvim-typescript/__init__.py", line 74, in reload                                                               
    self._client.reload(filename, tmpfile.name)                                                                                                                                               
  File "/home/emikkva/.config/nvim/plugged/deoplete-typescript/rplugin/python3/nvim-typescript/client.py", line 165, in reload                                                                
    response = self.send_request("reload", args, True)                                                                                                                                        
  File "/home/emikkva/.config/nvim/plugged/deoplete-typescript/rplugin/python3/nvim-typescript/client.py", line 95, in send_request                                                           
    self.__send_data_to_server(request)                                                                                                                                                       
  File "/home/emikkva/.config/nvim/plugged/deoplete-typescript/rplugin/python3/nvim-typescript/client.py", line 59, in __send_data_to_server                                                  
    Client.__server_handle.stdin.write("\n")                                                                                                                                                  
BrokenPipeError: [Errno 32] Broken pipe 
```

Is this a bug / issue in deoplete-typescript, or related to the neovim version?

**Comment by mhartington** [comment]
Hmm, what does `tsc -v` return?
Also, how could I got recreate this?

**Comment by mvalkon** [comment]
@mhartington thanks, turns out that a specific script for one of our repositories had modified my system node and npm version to some age-old version, completely breaking everything that currently uses npm.. I just did not notice this until I tried to issue `tsc --version`. Apologies for the unnecessary issue.
